version: '3'
services:
  secret:
    image: ssst0n3/docker_secret:v1.4.1
    environment:
      - "DIR_SECRET=/secret"
      - "SECRET=MYSQL_PASSWORD_FILE,MYSQL_ROOT_PASSWORD_FILE"
    volumes:
      - source-analysis-system_secret:/secret
  source-analysis-system:
    image: ghcr.io/ssst0n3/source-analysis-system:v0.5.17
    restart: always
    ports:
      - "16080:8080"
    environment:
      WITH_FRONTEND: "true"
      LOCAL_LISTEN_PORT: 8080
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
      WAIT_HOST_CONNECT_TIMEOUT: 5
      DB_DRIVER_NAME: mysql
      DB_NAME: source-analysis-system
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: source-analysis-system
      DB_PASSWORD_FILE: /secret/MYSQL_PASSWORD_FILE
      DIR_SECRET: /secret
    volumes:
      - source-analysis-system_secret:/secret
  db:
    depends_on:
      - secret
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - source-analysis-system_db:/var/lib/mysql
      - source-analysis-system_secret:/secret
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secret/MYSQL_ROOT_PASSWORD_FILE
      MYSQL_PASSWORD_FILE: /secret/MYSQL_PASSWORD_FILE
      MYSQL_USER: source-analysis-system
      MYSQL_DATABASE: source-analysis-system

volumes:
  source-analysis-system_db:
  source-analysis-system_secret:
