version: '3'
services:
  source-analysis-system:
#    build: .
    environment:
      - "DEBUG=true"

  secret:
    environment:
      - "DEVELOPMENT=true"
    volumes:
      - /tmp/secret:/tmp/secret

  db:
    ports:
      - "16036:3306"

  adminer:
    image: adminer:4
    restart: always
    ports:
      - "16088:8080"