version: '3'
services:
  source-analysis-system:
    build: .
    environment:
    - "ALLOW_ORIGINS=http://127.0.0.1:8080,http://localhost:8080,http://127.0.0.1:8081,http://localhost:8081"
    - "DEBUG=true"

  secret:
    environment:
      - "DEVELOPMENT=true"
    volumes:
      - /tmp/secret:/tmp/secret

  db:
    ports:
      - "16036:3306"

  adminer:
    image: adminer:4
    restart: always
    ports:
      - "16088:8080"
